name: Go-Check
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: Verify Go Mod and Go Sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
