name: Lint
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr:
    name: Run PR Title Linter
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
